### ISSUE TITLE
Invalid block type: ProxiBlue_GiftPromo_Block_Banners_Placement

### ISSUE THREAD

**Issue by ProxiBlue** [ProxiBlue/GiftPromo#2]
Hello, I checked my error log earlier today and it is completely full with the following error.... 

exception 'Mage_Core_Exception' with message 'Invalid block type: ProxiBlue_GiftPromo_Block_Banners_Placement' in /domains/tower-health.co.uk/http/app/Mage.php:595
Stack trace:
#0 /domains/tower-health.co.uk/http/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /domains/tower-health.co.uk/http/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('giftpromo/banne...', Array)
#2 /domains/tower-health.co.uk/http/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('giftpromo/banne...', 'banner_right_bo...')
#3 /domains/tower-health.co.uk/http/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('giftpromo/banne...', 'banner_right_bo...')............................

Is this an error that is easy to fix or is it just a plugin that is conflicting?

Thanks,
Harrison

**Comment by ProxiBlue** [comment]
Seems there is a leftover mention of teh dropped banners code here:

https://github.com/ProxiBlue/GiftPromo/blob/master/app/design/frontend/rwd/default/layout/giftpromo.xml#L50

and some more as well.

Looks like the RWD giftpromo.xml was never updated.

**Comment by ProxiBlue** [comment]
https://github.com/ProxiBlue/GiftPromo/releases/tag/2.40.2
